version: "3"
services:
   db:
      image: mysql:8
      environment:
         - MYSQL_ROOT_PASSWORD=delta1071$$
         - MYSQL_USER=myuser
         - MYSQL_PASSWORD=delta1071$$
         - MYSQL_DATABASE=ticketingsystem

   node-app:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "3000:3000"
      environment:
         - DB_NAME=ticketingsystem
         - DB_USER=myuser
         - DB_PASSWORD=delta1071$$
         - DB_HOST=db
         - DB_DIALECT=mysql
         - DB_POOL_MAX=5
         - DB_POOL_MIN=0
         - DB_POOL_ACQUIRE=30000
         - DB_POOL_IDLE=10000
      restart: on-failure
      depends_on: db
