# Use the official MySQL 8 image as the base image
FROM mysql:8

# Set environment variables for configuring the MySQL server
ENV MYSQL_ROOT_PASSWORD=delta1071$$
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=delta1071$$
ENV MYSQL_DATABASE=ticketingsystem

# Expose the default MySQL port
EXPOSE 3306